name: CI GIT Pipeline

on:
    push:
        branches:
            - dev
            - master
    pull_request:
        branches:
            - dev
            - master
            
            
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'temurin'
                        
            - name: Install local JAR dependencies
              working-directory: TourGuide
              run: |
                mvn install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
                mvn install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
                mvn install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
                
            - name: Build and Test with Maven
              working-directory: TourGuide
              run: mvn clean install
                
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: tourguide-jar
                path: ./TourGuide/target/*.jar